namespace Billbee.Api.Client.Enums
{
    public enum PaymentTypeEnum
    {
        Bankueberweisung = 1,
        Nachnahme = 2,
        PayPal = 3,
        Barzahlung = 4,
        Gutschein = 6,
        Sofortüberweisung = 19,
        /// <summary>
        /// etsy
        /// </summary>
        MoneyOrder = 20, // etsy
        /// <summary>
        /// etsy ck
        /// </summary>
        Check = 21, // etsy ck
        Andere = 22,
        Lastschrift = 23,
        Moneybookers = 24,
        KLARNA_Invoice = 25,
        Rechnung = 26,
        Moneybookers_Kreditkarte = 27,
        Moneybookers_Lastschrift = 28,
        BILLPAY_Rechnung = 29,
        BILLPAY_Lastschrift = 30,
        Kreditkarte = 31,
        Maestro = 32,
        iDEAL = 33,
        EPS = 34,
        P24 = 35,
        ClickAndBuy = 36,
        GiroPay = 37,
        Novalnet_Lastschrift = 38,
        KLARNA_PartPayment = 39,
        iPayment_CC = 40,
        Billsafe = 41,
        Testbestellung = 42,
        WireCard_Kreditkarte = 43,
        AmazonPayments = 44,
        Secupay_Kreditkarte = 45,
        Secupay_Lastschrift = 46,
        WireCard_Lastschrift = 47,
        EC = 48,
        Paymill_Kreditkarte = 49,
        Novalnet_Kreditkarte = 50,
        Novalnet_Rechnung = 51,
        Novalnet_PayPal = 52,
        Paymill = 53,
        Rechnung_PayPal = 54,
        Selekkt = 55,
        Avocadostore = 56,
        DirectCheckout = 57,
        Rakuten = 58,
        Vorkasse = 59,
        Kommissionsabrechnung = 60,
        Amazon_Marketplace = 61,
        Amazon_Payments_Advanced = 62,
        Stripe = 63,
        BILLPAY_PayLater = 64,
        PostFinance = 65,
        iZettle = 66,
        SumUp = 67,
        payleven = 68,
        atalanda = 69,
        Saferpay_Kreditkarte = 70,
        WireCard_PayPal = 71,
        Micropayment = 72,
        Ratenkauf = 73,
        Wayfair = 74, // baranski
        MangoPay_PayPal = 75,
        MangoPay_Sofortueberweisung = 76,
        MangoPay_Kreditkarte = 77,
        MangoPay_iDeal = 78,
        PayPal_Express = 79,
        PayPal_Lastschrift = 80,
        PayPal_Kreditkarte = 81,
        Wish = 82,
        Bancontact_Mister_Cash = 83,
        Belfius_Direct_Net = 84,
        KBC_CBC_Betaalknop = 85,
        Novalnet_Przelewy24 = 86,
        Novalnet_Vorkasse = 87,
        Novalnet_Instantbank = 88,
        Novalnet_IDEAL = 89,
        Novalnet_EPS = 90,
        Novalnet_GiroPay = 91,
        Novalnet_Barzahlen = 92,
        Real = 93,
        Fruugo = 94,
        Cdiscount = 95,
        PayDirekt = 96,
        EtsyPayments = 97,
        KLARNA = 98,
        limango = 99,
        SantanderRatenkauf = 100,
        SantanderRechnungskauf = 101,
        Cashpresso = 102,
        Tipser = 103,
        Ebay = 104,
        Mollie = 105,
        MollieInvoice = 106,
        MollieCreditCard = 107,
        MollieSofort = 108,
        MollieGiroPay = 109,
        MollieMaestro = 110,
        MollieKlarnaPayLater = 111,
        MolliePayPal = 112,
        ApplePay = 113,
        Braintree = 114,
        BraintreeCreditCard = 115,
        BraintreePayPal = 116,
        MollieIdeal = 117,
        Scalapay = 118,
        OttoPayments = 119,
        IdealoDirektkaufPayments = 120,
        EasyCredit = 121,
        MollieApplePay = 122,
        MollieEPS = 123,
        CrefoPayPrepaid = 124,
        MollieBancontact = 125,
        MolliePrzelewy24 = 126,
        MollieKlarnaRatenkauf =127,
        MollieKlarnaSliceit =128,
    }
}
